package com.examen.agenda.model;
// Generated 18/06/2018 09:22:35 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;


/**
 * CatArea generated by hbm2java
 */
@Entity
@Table(name = "cat_area", catalog = "agenda")
public class CatArea {

	private Integer idArea;
	private String nombreArea;
	private Set<OPersonaEmpresa> OPersonaEmpresas = new HashSet<OPersonaEmpresa>(0);

	public CatArea() {
	}

	public CatArea(Integer idArea, String nombreArea) {
		this.idArea = idArea;
		this.nombreArea = nombreArea;
	}

	public CatArea(Integer idArea, String nombreArea, Set<OPersonaEmpresa> OPersonaEmpresas) {
		this.idArea = idArea;
		this.nombreArea = nombreArea;
		this.OPersonaEmpresas = OPersonaEmpresas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_area", unique = true, nullable = false)
	public Integer getIdArea() {
		return this.idArea;
	}

	public void setIdArea(Integer idArea) {
		this.idArea = idArea;
	}

	@Column(name = "nombre_area", nullable = false, length = 85)
	public String getNombreArea() {
		return this.nombreArea;
	}

	public void setNombreArea(String nombreArea) {
		this.nombreArea = nombreArea;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catArea")
	public Set<OPersonaEmpresa> getOPersonaEmpresas() {
		return this.OPersonaEmpresas;
	}

	public void setOPersonaEmpresas(Set<OPersonaEmpresa> OPersonaEmpresas) {
		this.OPersonaEmpresas = OPersonaEmpresas;
	}

}
