package com.examen.agenda.model;
// Generated 18/06/2018 09:22:35 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatEmpresa generated by hbm2java
 */
@Entity
@Table(name = "cat_empresa", catalog = "agenda")
public class CatEmpresa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5824704748423331384L;
	
	private Integer idEmpresa;
	private String empresa;
	private String rubro;
	private Set<OPersonaEmpresa> OPersonaEmpresas = new HashSet<OPersonaEmpresa>(0);

	public CatEmpresa() {
	}

	public CatEmpresa(Integer idEmpresa, String empresa) {
		this.idEmpresa = idEmpresa;
		this.empresa = empresa;
	}

	public CatEmpresa(Integer idEmpresa, String empresa, String rubro, Set<OPersonaEmpresa> OPersonaEmpresas) {
		this.idEmpresa = idEmpresa;
		this.empresa = empresa;
		this.rubro = rubro;
		this.OPersonaEmpresas = OPersonaEmpresas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_empresa", unique = true, nullable = false)
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "empresa", nullable = false, length = 85)
	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	@Column(name = "rubro", length = 45)
	public String getRubro() {
		return this.rubro;
	}

	public void setRubro(String rubro) {
		this.rubro = rubro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catEmpresa")
	public Set<OPersonaEmpresa> getOPersonaEmpresas() {
		return this.OPersonaEmpresas;
	}

	public void setOPersonaEmpresas(Set<OPersonaEmpresa> OPersonaEmpresas) {
		this.OPersonaEmpresas = OPersonaEmpresas;
	}

}
