package com.examen.agenda.model;
// Generated 18/06/2018 09:22:35 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatTipoPersona generated by hbm2java
 */
@Entity
@Table(name = "cat_tipo_persona", catalog = "agenda")
public class CatTipoPersona implements java.io.Serializable {

	private Integer idTipoPersona;
	private String tipoPersona;
	private Set<OPersona> OPersonas = new HashSet<OPersona>(0);

	public CatTipoPersona() {
	}

	public CatTipoPersona(Integer idTipoPersona, String tipoPersona) {
		this.idTipoPersona = idTipoPersona;
		this.tipoPersona = tipoPersona;
	}

	public CatTipoPersona(Integer idTipoPersona, String tipoPersona, Set<OPersona> OPersonas) {
		this.idTipoPersona = idTipoPersona;
		this.tipoPersona = tipoPersona;
		this.OPersonas = OPersonas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_tipo_persona", unique = true, nullable = false)
	public Integer getIdTipoPersona() {
		return this.idTipoPersona;
	}

	public void setIdTipoPersona(Integer idTipoPersona) {
		this.idTipoPersona = idTipoPersona;
	}

	@Column(name = "tipo_persona", nullable = false, length = 45)
	public String getTipoPersona() {
		return this.tipoPersona;
	}

	public void setTipoPersona(String tipoPersona) {
		this.tipoPersona = tipoPersona;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catTipoPersona")
	public Set<OPersona> getOPersonas() {
		return this.OPersonas;
	}

	public void setOPersonas(Set<OPersona> OPersonas) {
		this.OPersonas = OPersonas;
	}

}
