package com.examen.agenda.model;
// Generated 18/06/2018 09:22:35 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * OPersonaEmpresaId generated by hbm2java
 */
@Embeddable
public class OPersonaEmpresaId implements java.io.Serializable {

	private Integer idPersona;
	private Integer idEmpresa;

	public OPersonaEmpresaId() {
	}

	public OPersonaEmpresaId(Integer idPersona, Integer idEmpresa) {
		this.idPersona = idPersona;
		this.idEmpresa = idEmpresa;
	}
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_persona", nullable = false)
	public Integer getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(Integer idPersona) {
		this.idPersona = idPersona;
	}
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id_empresa", nullable = false)
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OPersonaEmpresaId))
			return false;
		OPersonaEmpresaId castOther = (OPersonaEmpresaId) other;

		return (this.getIdPersona() == castOther.getIdPersona()) && (this.getIdEmpresa() == castOther.getIdEmpresa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPersona();
		result = 37 * result + this.getIdEmpresa();
		return result;
	}

}
